import Head from "next/head";
import Loader from "../components/Loader";
import Card from "../components/Card";
import { supabase } from "../lib/supabase";
import Button from "../components/Button";
import StickyNavbar from "../components/StickyNavbar";
import { useEffect, useState } from "react";
import Link from "next/link";
export default function Home() {
  const [notes, setNotes] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      let { data } = await supabase
        .from("notes")
        .select("slug, title, markdown, id");
      setNotes(data);
    };
    fetchData();
  }, []);
  return (
    <div className="">
      <Head>
        <title>My notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StickyNavbar>
        <div className="pb-4">
          <Link href="/new">
            <Button>Add a new note</Button>
          </Link>
        </div>
      </StickyNavbar>

      <main className={"main__grid"}>
        {!notes ? (
          <div className="flex justify-center w-screen items-center">
            <Loader />
          </div>
        ) : (
          notes?.map((note) => (
            <Link key={note.id} href={`/notes/${note.slug}`}>
              <Card note={note} />
            </Link>
          ))
        )}
      </main>
    </div>
  );
}
